runtime: python38
instance_class: B8

basic_scaling:
  max_instances: 11
  idle_timeout: 10m
 
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301


entrypoint: gunicorn -b 0.0.0.0:8080 transitapp:server --timeout 800




