service: default 
runtime: python37
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 0
  max_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 20

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301


entrypoint: gunicorn -b 0.0.0.0:8080 transit:server




